PasteleriaYummy/ViewModels/CarritoComprasViewModel.cs
using EdgarAparicio.PastelesYummy.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PasteleriaYummy.ViewModels
{
    public class CarritoComprasViewModel
    {
        public DataCarritoCompras DataCarritoCompras { get; set; }

        public decimal TotalCarritoCompras { get; set; }
    }
}

PasteleriaYummy/Controllers/CarritoComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EdgarAparicio.PastelesYummy.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PasteleriaYummy.ViewModels;

namespace PasteleriaYummy.Controllers
{
    [Authorize]
    public class CarritoComprasController : Controller
    {
        private readonly IPastel pastelRepositorio;
        private readonly DataCarritoCompras carritoComprasRepositorio;
        public CarritoComprasController(IPastel pastel, DataCarritoCompras carritoCompras)
        {
            pastelRepositorio = pastel;
            carritoComprasRepositorio = carritoCompras;
        }

        public ViewResult Index()
        {
            var articulos = carritoComprasRepositorio.ObtenerListaArticulosCarritoCompras();
            carritoComprasRepositorio.ListaArticulosCarritoCompras = articulos;

            var carritoComprasViewModel = new CarritoComprasViewModel
            {
                DataCarritoCompras = carritoComprasRepositorio,
                TotalCarritoCompras = carritoComprasRepositorio.ObtenerTotalCarritoCompras()
            };

            return View(carritoComprasViewModel);
        }

        public RedirectToActionResult AgregarArticuloCarritoCompras(int idPastel)
        {
            var pastelSeleccionado = pastelRepositorio.ObtenerListaPasteles.FirstOrDefault(p => p.PastelId == idPastel);
            if(pastelSeleccionado != null)
            {
                carritoComprasRepositorio.AgregarAlCarrito(pastelSeleccionado, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RetirarArticuloCarritoCompras(int idPastel)
        {
            var pastelSeleccionado = pastelRepositorio.ObtenerListaPasteles.FirstOrDefault(p => p.PastelId == idPastel);
            if(pastelSeleccionado != null)
            {
                carritoComprasRepositorio.RetirarDeCarrito(pastelSeleccionado);
            }
            return RedirectToAction("Index");
        }

    }
}

PasteleriaYummy/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EdgarAparicio.PastelesYummy.Business.Entity;
using EdgarAparicio.PastelesYummy.Data;
using Microsoft.AspNetCore.Mvc;

namespace PasteleriaYummy.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedido pedidoRepositorio;
        private readonly DataCarritoCompras carritoComprasRepositorio;

        public PedidoController(IPedido pedido, DataCarritoCompras carritoCompras)
        {
            this.pedidoRepositorio = pedido;
            carritoComprasRepositorio = carritoCompras;
        }
        
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            var items = carritoComprasRepositorio.ObtenerListaArticulosCarritoCompras();
            carritoComprasRepositorio.ListaArticulosCarritoCompras = items;
            if (carritoComprasRepositorio.ListaArticulosCarritoCompras.Count == 0)
            {
                ModelState.AddModelError("", "Tu carrito esta vacio, agrega algunos pasteles");
            }

            if (ModelState.IsValid)
            {
                pedidoRepositorio.CrearPedido(pedido);
                carritoComprasRepositorio.LimpiarCarrito();
                return RedirectToAction("CheckoutCompleto");
            }
            return View(pedido);
        }

        public IActionResult CheckoutCompleto()
        {
            ViewBag.CheckoutCompletoMensaje = "Gracias por tu compra, que disfrutes de los deliciosos pasteles!";
            return View();
        }

    }
}

PasteleriaYummy/Views/CarritoCompras/Index.cshtml
@model PasteleriaYummy.ViewModels.CarritoComprasViewModel

<h2>Tu carrito de compras</h2>
<h4>Aqui tienes tus deliciosos pasteles en tu carrito de compras</h4>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Cantidad seleccionada</th>
            <th>Pastel</th>
            <th class="text-right">Precio</th>
            <th class="text-right">Subtotal</th>
            <th class="text-center">Retirar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var linea in Model.DataCarritoCompras.ListaArticulosCarritoCompras)
        {
            <tr>
                <td class="text-center">@linea.Cantidad</td>
                <td class="text-left">@linea.Pastel.Nombre</td>
                <td class="text-right">@linea.Pastel.Precio.ToString("c")</td>
                <td class="text-right">
                    @((linea.Cantidad * linea.Pastel.Precio).ToString("c"))
                </td>
                <td class="text-center"> 
                    <a class="btn btn-lg"
                       asp-controller="CarritoCompras" asp-action="RetirarArticuloCarritoCompras"
                       asp-route-idPastel="@linea.Pastel.PastelId">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.TotalCarritoCompras.ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" asp-controller="Pedido" asp-action="Checkout">Checkout</a>
</div>