PasteleriaYummy/Controllers/CarritoComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EdgarAparicio.PastelesYummy.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PasteleriaYummy.ViewModels;

namespace PasteleriaYummy.Controllers
{
    [Authorize]
    public class CarritoComprasController : Controller
    {
        private readonly IPastel pastelRepositorio;
        private readonly DataCarritoCompras carritoComprasRepositorio;
        public CarritoComprasController(IPastel pastel, DataCarritoCompras carritoCompras)
        {
            pastelRepositorio = pastel;
            carritoComprasRepositorio = carritoCompras;
        }

        public ViewResult Index()
        {
            var articulos = carritoComprasRepositorio.ObtenerListaArticulosCarritoCompras();
            carritoComprasRepositorio.ListaArticulosCarritoCompras = articulos;

            var carritoComprasViewModel = new CarritoComprasViewModel
            {
                DataCarritoCompras = carritoComprasRepositorio,
                TotalCarritoCompras = carritoComprasRepositorio.ObtenerTotalCarritoCompras()
            };

            return View(carritoComprasViewModel);
        }

        public RedirectToActionResult AgregarArticuloCarritoCompras(int idPastel)
        {
            var pastelSeleccionado = pastelRepositorio.ObtenerListaPasteles.FirstOrDefault(p => p.PastelId == idPastel);
            if(pastelSeleccionado != null)
            {
                carritoComprasRepositorio.AgregarAlCarrito(pastelSeleccionado, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RetirarArticuloCarritoCompras(int idPastel)
        {
            var pastelSeleccionado = pastelRepositorio.ObtenerListaPasteles.FirstOrDefault(p => p.PastelId == idPastel);
            if(pastelSeleccionado != null)
            {
                carritoComprasRepositorio.RetirarDeCarrito(pastelSeleccionado);
            }
            return RedirectToAction("Index");
        }

    }
}

PasteleriaYummy/Controllers/PastelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EdgarAparicio.PastelesYummy.Business.Entity;
using EdgarAparicio.PastelesYummy.Business.Entity.ViewModels;
using EdgarAparicio.PastelesYummy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;

namespace PasteleriaYummy.Controllers
{
    public class PastelController : Controller
    {
        private readonly IPastel pastelRepositorio;
        private readonly ICategoria categoriaRepositorio;

        public PastelController(IPastel pastel, ICategoria categoria)
        {
            pastelRepositorio = pastel;
            categoriaRepositorio = categoria;
        }

        //public IPastel Pastel { get; }
        //public ICategoria Categoria { get; }


        //Se define de mejor manera en el siguiente metodo que ya incluye dropdownlist
        //public ViewResult MostrarListaPasteles()
        //{
        //    //ViewBag.CategoriaActual = "Pasteles de Queso";
        //    //return View(pastelRepositorio.ObtenerListaPasteles);

        //    //Para no pasar un viewbag y un obtenerlistaPasteles, se creo una entidad de vista ViewModel llamado ListaPastelesViewModel
        //    //que contiene las propiedades que se quieren mostar y ahora en la vista ya no espera una entidad pastel sino una listaPastelesViewModel

        //    ListaPastelesViewModels listaPastelesViewModel = new ListaPastelesViewModels();
        //    listaPastelesViewModel.Pasteles = pastelRepositorio.ObtenerListaPasteles;
        //    listaPastelesViewModel.CategoriaActual = "Pasteles de Queso";
        //    return View(listaPastelesViewModel);
        //}

        public ViewResult MostrarListaPasteles(string categoriaNombre)
        {
            IEnumerable<Pastel> listaPasteles;
            string categoriaActual;
            if (string.IsNullOrEmpty(categoriaNombre))
            {
                listaPasteles = pastelRepositorio.ObtenerListaPasteles.OrderBy(o => o.PastelId);
                categoriaActual = "Todos los pasteles";
            }
            else
            {
                listaPasteles = pastelRepositorio.ObtenerListaPasteles
                    .Where(p => p.Categoria.CategoriaNombre == categoriaNombre)
                    .OrderBy(o => o.PastelId);
                categoriaActual = categoriaRepositorio.ObtenerListaCategorias
                    .FirstOrDefault(c => c.CategoriaNombre == categoriaNombre)
                    ?.CategoriaNombre;
            }

            //var listaPastelesViewModel = new ListaPastelesViewModels
            //{
            //    Pasteles = listaPasteles,
            //    CategoriaActual = categoriaActual
            //};
            return View(
                new ListaPastelesViewModels
                {
                    Pasteles = listaPasteles,
                    CategoriaActual= categoriaActual
                });
        }




        public IActionResult Detalles(int id)
        {
            var pastel = pastelRepositorio.ObtenerPastelPorId(id);
            if (pastel == null)
                return NotFound();
            return View(pastel);
        }
    }
}

PasteleriaYummy/Views/Pastel/Detalles.cshtml
@*Ya se agrego la referencia en _viewImports*@
@model Pastel

<h2>@Model.Nombre</h2>

<div class="thumbnail">
    <img alt="@Model.Nombre" src="@Model.ImagenUrl">
    <div class="caption-full">
        <h3 class="pull-right">@Model.Precio</h3>
        <h3>
            <a href="#">@Model.Nombre</a>
        </h3>
        <h4>@Model.DescripcionCorta</h4>
        <p>@Model.DescripcionLarga</p>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="CarritoCompras"
                   asp-action="AgregarArticuloCarritoCompras"
                   asp-route-idPastel="@Model.PastelId">Agregar al carrito</a>
            </p>
        </div>
    </div>
</div>

PasteleriaYummy/Views/Pastel/MostrarListaPasteles.cshtml
@*@model IEnumerable<EdgarAparicio.PastelesYummy.Business.Entity.Pastel>*@
@*Para ya no recibir un Ienumerable de pasteles, ahora se recibe un viewModel llamado ListaPastelesViewModel *@

@*@model EdgarAparicio.PastelesYummy.Business.Entity.ViewModels.ListaPastelesViewModels*@

@*Y para no agregar tod ala referencia desde EgarAparicio.Pasteles..... se agrego una vista de importaciones en donde se agrega la referencia
y aqui solo agregamos el modelo a recibir*@
@model ListaPastelesViewModels


<h3>@Model.CategoriaActual</h3>
@foreach (var pastel in Model.Pasteles)
{
    @*Se pasa codigo a una partial view _TarjetaPastelPartialView
        <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@pastel.ImagenThumbnailUrl" alt="">
            <div class="caption">
                <h3 class="pull-right">@pastel.Precio.ToString("c")</h3>
                <h3>
                    <a asp-controller="Pastel" asp-action="Detalles" asp-route-id="@pastel.PastelId">@pastel.Nombre</a>
                </h3>
                <p>@pastel.DescripcionCorta</p>
            </div>
        </div>
    </div>*@

    <partial name="_TarjetaPastelPartialView" model="pastel" />

}